name: Deploy WordPress.org assets and readme

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy_assets:
    name: Deploy readme and assets to WordPress.org
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: alpaca-issue-tracker
          IGNORE_OTHER_FILES: true
